### ISSUE TITLE
Why the whole source code should be named as 'udiskxxxyyy'?

### ISSUE THREAD

**Issue by cathay4t** [storaged-project/storaged#107]
Any particular reason we should keep udisk name in all files/functions besides public library and headers?

Sorry, I failed to find the storaged mailing list for this kind of question.

**Comment by vpodzime** [comment]
Thanks for pointing this out! I was wondering about the same last week.

**Comment by vpodzime** [comment]
And on a related note -- do we really need the *linux* part for the names? Is storaged supposed to work on any other system than GNU/Linux?

**Comment by tsmetana** [comment]
The original udisks daemon ran also on FreeBSD at least. Though I'm unsure today's storaged could be made to work there too. I agree those things are little bit annoying: changing the files and function names is not completely risk-free and there was always some more important work to do...

**Comment by cathay4t** [comment]
Closing as upstream could live with this.

**Comment by vpodzime** [comment]
> Closing as upstream could live with this.

Nice justification! :D
