### ISSUE TITLE
Should add check existing of `eject` in `configure.ac`

### ISSUE THREAD

**Issue by cathay4t** [storaged-project/storaged#127]
As storaged is using `eject` tool for `handle_eject()`, we'd better make sure that tool exists in `configure.ac` via `AC_CHECK_PROG`

And all other tools use by `udisks_daemon_launch_spawned_job_sync()` should also been checked.

**Comment by tsmetana** [comment]
This looks bogus to me: the tools do not have to be present in the build environment for a successful build: It would only make the build root bigger. The external tools have to be available in the runtime and that's something we don't control: it's up to downstreams to handle dependencies correctly.

**Comment by cathay4t** [comment]
Sure. If you say so. I will try to create one file to indicate extra runtime dependency in case `downstreams packager` don't read full project code.

**Comment by tsmetana** [comment]
Hm, "If I say so" does by no mean imply "sure". :)

There is already a packaging/ directory where we have a spec file template so far. Adding instructions or templates for other distributions might make the downstream maintainers life easier for sure. 

Thanks.
