### ISSUE TITLE
configure: error: BTRFS support requested but header or library not found

### ISSUE THREAD

**Issue by tasleson** [storaged-project/storaged#152]
Fully patched F24, git tree d701044631509ec4dfb142485568e68ab1f7dc8f

``` bash
$ git clean && ./autogen.sh --enable-modules --enable-debug
...
checking "libblockdev-btrfs presence"... no
configure: error: BTRFS support requested but header or library not found
```

``` bash
$ rpm -qa | grep libblockdev | sort
libblockdev-1.6-1.fc24.x86_64
libblockdev-btrfs-1.6-1.fc24.x86_64
libblockdev-btrfs-devel-1.6-1.fc24.x86_64
libblockdev-crypto-1.6-1.fc24.x86_64
libblockdev-crypto-devel-1.6-1.fc24.x86_64
libblockdev-devel-1.6-1.fc24.x86_64
libblockdev-dm-1.6-1.fc24.x86_64
libblockdev-dm-devel-1.6-1.fc24.x86_64
libblockdev-fs-1.6-1.fc24.x86_64
libblockdev-fs-devel-1.6-1.fc24.x86_64
libblockdev-kbd-1.6-1.fc24.x86_64
libblockdev-kbd-devel-1.6-1.fc24.x86_64
libblockdev-loop-1.6-1.fc24.x86_64
libblockdev-loop-devel-1.6-1.fc24.x86_64
libblockdev-mdraid-1.6-1.fc24.x86_64
libblockdev-mdraid-devel-1.6-1.fc24.x86_64
libblockdev-mpath-1.6-1.fc24.x86_64
libblockdev-part-1.6-1.fc24.x86_64
libblockdev-part-devel-1.6-1.fc24.x86_64
libblockdev-swap-1.6-1.fc24.x86_64
libblockdev-swap-devel-1.6-1.fc24.x86_64
libblockdev-utils-1.6-1.fc24.x86_64
libblockdev-utils-devel-1.6-1.fc24.x86_64
```
AFAIK I have all the dependencies.

**Comment by vpodzime** [comment]
> AFAIK I have all the dependencies.

You need libblockdev >= 2.1 to compile storaged on the *master* branch. On *master-libblockdev* this is handled in a better way by checking the presence and version of the ``blockdev.pc`` (pkg-config) file.

**Comment by tasleson** [comment]
@vpodzime 

- Any reason configure.ac isn't checking for this?
- Will newer versions of liblockdev be released for F24?

**Comment by vpodzime** [comment]
> Any reason configure.ac isn't checking for this?

Yes, I have no idea how something like that could be done in ``configure.ac``. As I mentioned above, this is handled properly on the *master-libblockdev* branch where *libblockdev* is used as a library, not just its plugins as standalone libraries. There we can check the version of the pkg-config *blockdev* package. But I have no idea how to do it on *master* branch.

**Comment by vpodzime** [comment]
> Will newer versions of liblockdev be released for F24?

I built libblockdev-2.1-2 for F24 and F25 in https://copr.fedorainfracloud.org/coprs/vpodzime/libblockdev. But I don't really want to properly update the package in older releases because it's a major release breaking the API and bumping so names/versions.

**Comment by tasleson** [comment]
>But I don't really want to properly update the package in older releases because it's a 
>major release breaking the API and bumping so names/versions.

Can you please elaborate on why you don't want to do this?

**Comment by tasleson** [comment]
@vpodzime I was simply thinking that storaged configure.ac could use: 
`PKG_CHECK_MODULES([blockdev], [blockdev >= 2.1])`

What am I missing?

**Comment by vpodzime** [comment]
> Can you please elaborate on why you don't want to do this?

AFAICT, one shouldn't  update libraries to incompatible versions in released versions of Fedora.

**Comment by vpodzime** [comment]
> @vpodzime I was simply thinking that storaged configure.ac could use:
> PKG_CHECK_MODULES([blockdev], [blockdev >= 2.1])
> 
> What am I missing?

The pkg-config stuff is for the *libblockdev* library. But on *master* branch, storaged is using the plugins as standalone libraries. And thus it doesn't need require the library itself. The plugins don't have pkg-config files.

**Comment by cathay4t** [comment]
So are we telling Fedora 24/25 developer `go ahead wasting your time on debugging this problem or found us in IRC or this github issue`.

**Comment by tasleson** [comment]
>> Can you please elaborate on why you don't want to do this?

> AFAICT, one shouldn't update libraries to incompatible versions in released versions of Fedora.

Shouldn't this be packaged up as a new version of the library which can co-exist with the old one?  I see no technical reason why they couldn't both be installed on the same box at the same time right?  Isn't this the whole point of doing the versioning?  You created a new major release that isn't backwards compatible.

**Comment by vpodzime** [comment]
> Shouldn't this be packaged up as a new version of the library which can co-exist with the old one? I see no technical reason why they couldn't both be installed on the same box at the same time right? Isn't this the whole point of doing the versioning? You created a new major release that isn't backwards compatible.

Until this GH issue report appeared, I had no request for that. And considering the amount of packaging issues/work as well as struggle for users when doing ``dnf search libblockdev`` and similar, I'm not really sure it's worth all the struggle. It's really easy to enable a copr repository. For F25 and Rawhide there's *vtrefny/storage* copr repository which contains daily builds of all our storage-related projects.
