### ISSUE TITLE
Compile failure on master tree: udiskslogging.c:62:3: error: implicit declaration of function ‘g_log_structured’

### ISSUE THREAD

**Issue by cathay4t** [storaged-project/storaged#159]
Make failed on 5316c55
```
udiskslogging.c: In function ‘udisks_log’:
udiskslogging.c:62:3: error: implicit declaration of function ‘g_log_structured’ [-Werror=implicit-function-declaration]
   g_log_structured ("udisks", (GLogLevelFlags) level,
   ^~~~~~~~~~~~~~~~
udiskslogging.c:62:3: warning: nested extern declaration of ‘g_log_structured’ [-Wnested-externs]
cc1: some warnings being treated as errors
Makefile:953: recipe for target 'libudisks_daemon_la-udiskslogging.lo' failed
make[2]: *** [libudisks_daemon_la-udiskslogging.lo] Error 1
```

**Comment by cathay4t** [comment]
Failure found on Fedora 24.

Tried Fedora rawhide, compile pass with some warnings but no failure.

**Comment by tsmetana** [comment]
Ooops. I should have noticed this. The stuctured logging has been added in glib 2.49.3 according to the [glib changelog](https://git.gnome.org/browse/glib/tree/NEWS#n176). Fedora 24 with its glib 2.48.2 is too old for storaged now...

Therefore it's a [bug in configure.ac](https://github.com/storaged-project/storaged/blob/master/configure.ac#L136): PKG_CHECK_MODULES(GLIB, [glib-2.0 >= 2.36])...

**Comment by vpodzime** [comment]
@tsmetana, yeah, but I think we need to support older GLib releases too. I'll work on a patch that will deal with this.
