### ISSUE TITLE
The CI test results should be public

### ISSUE THREAD

**Issue by tsmetana** [storaged-project/storaged#192]
Hi, I think the automatic PR tests results should be uploaded to some public place. The "details" link leads to a place that almost nobody can access... This might be frustrating for the contributors: something has failed but they can't see what exactly.

**Comment by vojtechtrefny** [comment]
@vpodzime is already working on this

**Comment by tsmetana** [comment]
Ah. OK. Didn't know it. Thanks.

**Comment by vpodzime** [comment]
Done now, see the PR #189 for example (the "ci/x86_64/f_rawhide" check)
