### ISSUE TITLE
make install puts org.storaged.Storaged.conf in /usr/local/ on Fedora 22

### ISSUE THREAD

**Issue by trgill** [storaged-project/storaged#20]
Following the instructions in  README.md on Fedora 22
make install puts org.storaged.Storaged.conf in /usr/local/etc/dbus-1/system.d/.

d-bus reads the .conf files from /etc/dbus-1/system.d/. 

In this situation storaged immediately exits when on_name_lost() is called.

**Comment by phatina** [comment]
Try changing the default prefix by `./configure --prefix=/usr`, if you want to install on F22.

**Comment by trgill** [comment]
Thanks.  When I use the configure command you suggested it works.

Does it make sense to add something to the README?  

When there is a permissions problem storaged  exits and doesn't make it clear why.

**Comment by phatina** [comment]
It's default path from autotools.

What do you mean by permission problem? Can you paste the output, please?

**Comment by trgill** [comment]
I think this file needs to exist to grant root permission to "own" the name on d-bus.

/etc/dbus-1/system.d/org.storaged.Storaged.conf

If the file doesn't exist storaged exits (see log below).

To see the what I'm talking about:

rm /etc/dbus-1/system.d/org.storaged.Storaged.conf
systemctl restart dbus
systemctl restart storaged

There is a message that indicates "lost (or failed to acquire)", it might be helpful if the message included something about checking permissions. (?)


10:26:21.124:[14914]:[DEBUG]: uevent add /sys/devices/pci0000:00/0000:00:03.0/0000:08:00.1/host7/rport-7:0-0/target7:0:0/7:0:0:5/block/sdo [storagedlinuxprovider.c:1183, storaged_linux_provider_handle_uevent()]
10:26:21.124:[14914]:[DEBUG]: uevent add /sys/devices/pci0000:00/0000:00:03.0/0000:08:00.1/host7/rport-7:0-0/target7:0:0/7:0:0:6/block/sdp [storagedlinuxprovider.c:1183, storaged_linux_provider_handle_uevent()]
10:26:21.124:[14914]:[DEBUG]: uevent add /sys/devices/pci0000:00/0000:00:1f.2/ata5/host4/target4:0:0/4:0:0:0/block/sr0 [storagedlinuxprovider.c:1183, storaged_linux_provider_handle_uevent()]
10:26:21.124:[14914]:[INFO]: Initialization complete [storagedlinuxprovider.c:582, storaged_linux_provider_start()]
10:26:21.125:[14929]:[INFO]: Housekeeping initiated (0 seconds since last housekeeping) [storagedlinuxprovider.c:1294, housekeeping_thread_func()]
10:26:21.125:[14929]:[INFO]: Refreshing SMART data on /org/storaged/Storaged/drives/WDC_WD5003ABYX_18WERA0_WD_WMAYP7304483 (nowakeup=0) [storagedlinuxdriveobject.c:990, storaged_linux_drive_object_housekeeping()]
10:26:21.125:[14914]:[DEBUG]: Connected to the system bus [main.c:62, on_bus_acquired()]
10:26:21.125:[14939]:[INFO]: Entering cleanup thread [storagedstate.c:306, storaged_state_thread_func()]
10:26:21.125:[14939]:[INFO]: Cleanup check start [storagedstate.c:419, storaged_state_check_in_thread()]
10:26:21.125:[14939]:[INFO]: Cleanup check end [storagedstate.c:457, storaged_state_check_in_thread()]
10:26:21.125:[14914]:[INFO]: Lost (or failed to acquire) the name org.storaged.Storaged on the system message bus [main.c:76, on_name_lost()]
10:26:21.126:[14939]:[INFO]: Exiting cleanup thread [storagedstate.c:317, storaged_state_thread_func()]
10:26:21.126:[14914]:[NOTICE]: storaged daemon version 2.3.0 exiting [m

**Comment by phatina** [comment]
This type of error is usual in DBus terminology; so I guess, it's fine to leave it as is.
