### ISSUE TITLE
ISCSI Login does not take user/pass credentials.

### ISSUE THREAD

**Issue by mvollmer** [storaged-project/storaged#24]
I think they are needed, no?  Maybe I am confused.

**Comment by phatina** [comment]
I am going to push changes to address this issue soon. Thank you.

**Comment by mvollmer** [comment]
I have tested https://github.com/storaged-project/storaged/commit/2c1a208dea4591ecfb04e50a3cfd3481581ff54a and it works as expected. 

Our https://github.com/cockpit-project/cockpit/pull/2807 now depends on this and has a automated integration test.

**Comment by phatina** [comment]
Thank you very much; we can close this, now.
