### ISSUE TITLE
iSCSI SetInitiatorName should reject invalid names

### ISSUE THREAD

**Issue by mvollmer** [storaged-project/storaged#32]
Right now it is possible to set the initiator name to almost any string, but I understand that there are some restrictions.

**Comment by mvollmer** [comment]
Hmm, I tried to actually use "Hello?" as the initiator name, and could actually connect to a target just fine.  So maybe there isn't much to reject.  Cockpit can certainly help and point out probable mistakes, though.

**Comment by phatina** [comment]
> Hmm, I tried to actually use "Hello?" as the initiator name, and could actually connect to a target just fine. So maybe there isn't much to reject. Cockpit can certainly help and point out probable mistakes, though.

There is no special restriction placed for iSCSI Names (See [RFC-3720](https://www.ietf.org/rfc/rfc3720.txt)).

3.2.6.1. iSCSI Name Properties
==============================

iSCSI names have the following properties:

  - iSCSI names are globally unique.  No two initiators or targets can have the same name.
  - iSCSI names are permanent.  An iSCSI initiator node or target node has the same name for its lifetime.
  - iSCSI names do not imply a location or address.  An iSCSI initiator or target can move, or have multiple addresses. A change of address does not imply a change of name.
  - iSCSI names do not rely on a central name broker; the naming authority is distributed.
  - iSCSI names support integration with existing unique naming schemes.
  - iSCSI names rely on existing naming authorities.  iSCSI does not create any new naming authority.

**Comment by phatina** [comment]
Closing, since there **is not a strict definition** for an *invalid iSCSI Name*.
