### ISSUE TITLE
Export list of supported filesystems

### ISSUE THREAD

**Issue by mvollmer** [storaged-project/storaged#38]
So that a UI doesn't need to hardcode them.

**Comment by phatina** [comment]
@mvollmer, using the *master* branch: The object `/org/storaged/Storaged/Manager` has the interface `org.storaged.Storaged.Manager` with the property `SupportedFilesystems` which contains a list of all the supported filesystems by Storaged.

**Note:** The branch *udisks2* contains the corresponding interface.

Does this work for you?

**Comment by mvollmer** [comment]
Nice!  I'll try this soonish.

**Comment by mvollmer** [comment]
> Does this work for you?

Yes, it does, but now I am hesitant to actually make use of this in the UI...

While the listed filesystem types work with the Format method, they don't all work well enough, I am afraid.  For example, one can make a btrfs filesystem, but one can't mount it (maybe with the module?).  One can make a nilfs2 filesystem, but it is shown as "Unrecognized Data" afterwards.

Also, we shouldn't offer ext2 and ext3 in addition to ext4, that's just confusing.

So, what we'll probably do is to have a well maintained list of filesystems in our code, and then filter out types that are not supported by storaged.

**Comment by phatina** [comment]
That's a pitty. Can I improve this thing somehow? Any suggestions?

**Comment by mvollmer** [comment]
> Can I improve this thing somehow? Any suggestions?

No, the works needs to be done in Cockpit.
