### ISSUE TITLE
Debian Support

### ISSUE THREAD

**Issue by pawcioo132** [storaged-project/storaged#41]
I just wondering, storaged will be support for debian ? Or there is any other way to make it works on debian linux ?

**Comment by phatina** [comment]
Hi, I was tinkering with Ubuntu box and Storaged project some time ago. I was able to compile the core Storaged in Ubuntu environment. But there are some modules that depend on [libblockdev](https://github.com/rhinstaller/libblockdev), which isn't available there (I guess, Debian doesn't pack this, as well). When I have the time, I would definitely like to support these OS's :)

**Comment by andreas-fatal** [comment]
FYI, I've packaged storaged (modeled split after the fedora packages and disabled modules where dependencies where missing) and put it in Debian Experimental completely untested. Hope this helps.

https://tracker.debian.org/pkg/storaged

**Comment by phatina** [comment]
Thank you very much. I have already seen this repo and I am working on providing PPA's for Ubuntu, which will also pack volume_key, libblockdev and storaged.

**Comment by phatina** [comment]
I finished packaging all the missing bits required by the plugins. PPA's can be found at my [Launchpad](https://launchpad.net/~phatina).

[Storaged](https://launchpad.net/~phatina/+archive/ubuntu/storaged) has several dependencies which are available in separate PPA repositories:

* [isns-utils](https://launchpad.net/~phatina/+archive/ubuntu/isns-utils)
* [libblockdev](https://launchpad.net/~phatina/+archive/ubuntu/libblockdev)
* [open-iscsi](https://launchpad.net/~phatina/+archive/ubuntu/open-iscsi)
* [volume_key](https://launchpad.net/~phatina/+archive/ubuntu/volume-key)

Storaged has been tested on Ubuntu 15.10 (Wily Werewolf).

**Comment by andhe** [comment]
Hello, some feedback from the Debian camp. Thanks for packaging the dependencies. Your PPAs should serve as a good base for someone wanting to maintain those inside Debian. I've filed http://bugs.debian.org/820099 in the hope to find someone with time to properly maintain storaged package inside Debian and have it included in a future stable release. (I'm currently to short on time to do this properly myself.)

**Comment by Centril** [comment]
Any updates for ubuntu 16.04 and 16.10 perhaps ?
