### ISSUE TITLE
LVM2 Plugin: cache split using unsafe option (--splitcache)

### ISSUE THREAD

**Issue by tasleson** [storaged-project/storaged#46]
see: https://bugzilla.redhat.com/show_bug.cgi?id=1248972

**Comment by phatina** [comment]
The best solution to me is to introduce a new method `CacheDetach` as the inverse to `CacheAttach` to the interface `org.storaged.Storaged.LogicalVolume`.

Opinion(s)?

**Comment by phatina** [comment]
@tsmetana is working on rewriting **LVM** module to use [libblockdev](https://github.com/rhinstaller/libblockdev/) for LVM manipulation. We need to sync up...

**Comment by tsmetana** [comment]
Hi,
  I just pushed the first rewrite pass (to a [separate branch](https://github.com/tsmetana/storaged/commit/0a430e2080b858de4cdb3c40112f77817bb8b739)). It was only "mechanical" changes so far but I will try to fix the cache part with the rewrite.

**Comment by tsmetana** [comment]
@phatina: Sooo... Is [this](https://github.com/tsmetana/storaged/commit/506f7f3f9c17b5d09cb8b1e02e458b9d8d89f1ca) it?

**Comment by phatina** [comment]
> @phatina: Sooo... Is this it?

Yeah! Change the `@since` tag to `@since: 2.5.0` and you are done.

**Comment by tsmetana** [comment]
OK. Done.
