### ISSUE TITLE
storaged-lsm plugin config file is world readable

### ISSUE THREAD

**Issue by tasleson** [storaged-project/storaged#51]
`/etc/storaged/modules.conf.d/storaged_lsm.conf` is world readable.  As this file may contain sensitive data it should be only readable by `root`.

**Comment by phatina** [comment]
This seems to be only the packaging issue; which is fixed in:
  - [storaged-2.5.0-3.fc24](http://koji.fedoraproject.org/koji/taskinfo?taskID=13365376)
  - [storaged-2.5.0-3.fc25](http://koji.fedoraproject.org/koji/taskinfo?taskID=13365014)
