### ISSUE TITLE
storaged crash

### ISSUE THREAD

**Issue by mulkieran** [storaged-project/storaged#55]
I just crashed storaged by trying to create a cycle between an lvm VG and an mdraid raid array.

I was using Cockpit and I added an lv as a spare on the array. Then I tried to add the array as a physical volume of the VG. Then storaged crashed.

Contents of abrt directory:

```
[root@megadeth ccpp-2016-05-03-14:52:09-14087]# ls
abrt_version    coredump    hostname         os_info     pkg_release       time
analyzer        count       kernel           os_release  pkg_version       type
architecture    dso_list    last_occurrence  package     proc_pid_status   uid
cgroup          environ     limits           pid         pwd               username
cmdline         event_log   machineid        pkg_arch    reason            uuid
component       executable  maps             pkg_epoch   runlevel          var_log_messages
core_backtrace  global_pid  open_fds         pkg_name    sosreport.tar.xz
```

Is there anything that you would like me to upload from this directory? core_backtrace, coredump? The abrt-cli client seems broken on my machine, fyi.

**Comment by phatina** [comment]
Coredump, please.

**Comment by mulkieran** [comment]
[coredump.bz2.zip](https://github.com/storaged-project/storaged/files/248673/coredump.bz2.zip)

I hope this works. I used bzip to compress...the extra "zip" extension is just decoration to get past github's goofy filter.

**Comment by phatina** [comment]
What version of storaged did you use?

**Comment by mulkieran** [comment]
Installed Packages
Name        : storaged
Arch        : x86_64
Version     : 2.2.0
Release     : 3.el7
Size        : 1.8 M
Repo        : installed
From repo   : RHEL-7.2-Extra
Summary     : Disk Manager
URL         : https://github.com/storaged-project/storaged

Which I see is from last August, whoops.

I'll try to install from HEAD and see if I can reproduce.

**Comment by mulkieran** [comment]
Experiencing some minor problems...you decide if they are configuration errors or syntax or what.

I haven't installed any libblockdev plugins because this machine is running RHEL7 and they don't exist in standard RHEL7 repos. I don't want to have gradually more and more of installing stuff from source if I can avoid it.

Attached is the output of make.

[make.txt](https://github.com/storaged-project/storaged/files/248757/make.txt)

**Comment by phatina** [comment]
What version of storaged did you use? How did you configure it?

**Comment by mulkieran** [comment]
```./configure --enable-iscsi --enable-lvm2 --enable-lsm```

commit df4624dd13d1698ae1c3daefa61214d55a9a371a

Including configure output and make output from fresh build (with a bonus warning).
[configure.txt](https://github.com/storaged-project/storaged/files/252413/configure.txt)
[make.txt](https://github.com/storaged-project/storaged/files/252414/make.txt)
