### ISSUE TITLE
make check in po fails for storaged-2.0.0

### ISSUE THREAD

**Issue by tgurr** [storaged-project/storaged#6]
[...]
Making check in po
make[1]: Entering directory '/var/tmp/paludis/build/sys-apps-storaged-2.0.0/work/storaged-2.0.0/po'
INTLTOOL_EXTRACT="/usr/bin/intltool-extract" XGETTEXT="/usr/bin/xgettext" srcdir=. /usr/bin/intltool-update --gettext-package storaged --pot
rm -f missing notexist
srcdir=. /usr/bin/intltool-update -m
if [ -r missing -o -r notexist ]; then \
  exit 1; \
fi
Makefile:164: recipe for target 'check' failed
make[1]: Leaving directory '/var/tmp/paludis/build/sys-apps-storaged-2.0.0/work/storaged-2.0.0/po'
Makefile:483: recipe for target 'check-recursive' failed
The following files contain translations and are currently not in use. Please
consider adding these to the POTFILES.in file, located in the po/ directory.

modules/lvm2/data/org.storaged.Storaged.lvm2.policy.in
modules/lvm2/storagedlinuxlogicalvolume.c
modules/lvm2/storagedlinuxmanagerlvm2.c
modules/lvm2/storagedlinuxvolumegroup.c

If some of these files are left out on purpose then please add them to
POTFILES.skip instead of POTFILES.in. A file 'missing' containing this list
of left out files has been written in the current directory.
Please report to https://storaged-project.github.io
make[1]: *** [check] Error 1
make: *** [check-recursive] Error 1
[...]

**Comment by phatina** [comment]
Thank you for the report.  The problem is located in translations.  I am already working on this; fix is comming soon.
