### ISSUE TITLE
Using byte arrays for string data

### ISSUE THREAD

**Issue by tasleson** [storaged-project/storaged#62]
When looking at the interface today I noticed that some properties are returning byte arrays when a string would appear more appropriate, eg. 

org.storaged.Storaged.Block.PreferredDevice

returns 
```
[47,100,101,118,47,115,99,97,108,101,47,108,118,111,108,48,0]
```

or more easily digested as:

```
/dev/scale/lvol0
```

As this is part of a published interface, I'm guessing we cannot change them.

**Comment by tsmetana** [comment]
This is part of the "core" API inherited from udisks2. And since we want to maintain compatibility it's not going to go away I'm afraid.

**Comment by tasleson** [comment]
Well that is indeed ugly, but understandable.
