### ISSUE TITLE
configure fails after running autotools for storaged-2.0.0

### ISSUE THREAD

**Issue by tgurr** [storaged-project/storaged#7]
After running autotools ./configure fails with:

[...]
./configure: line 12293: syntax error near unexpected token `maximum'
./configure: line 12293: `GNOME_COMPILE_WARNINGS(maximum)'
[...]

Used versions:
* autoconf-2.69
* automake-1.15

**Comment by phatina** [comment]
Hi, I am using these packages with no problem:
- autoconf-2.69-17.fc21.noarch
- automake-1.14.1-5.fc21.noarch
- gnome-common-3.14.0-2.fc21.noarch

**Comment by phatina** [comment]
No response; closing as "Works for me".
