### ISSUE TITLE
L10N - how up to date are is Zanata ? Do you pull content ?

### ISSUE THREAD

**Issue by Jibec** [storaged-project/storaged#86]
Hi,
I feel like translation team are working on very outdated content ! Zanata says 

> Last Upload "10/09/15 14:41 by phatina"

I feel like we spent months to translate useless content, or maybe you do not have too much string changes ?
Please push up to date content and pull back our work regulary!

**Comment by tsmetana** [comment]
Hi. It's true we have not been very diligent pulling the translations from Zanata. Sorry for that. I have just pulled the new content and will push back once I sort out some fallout from the API renaming.

**Comment by Jibec** [comment]
It's the past, let's build the future with good collaboration :)

Our focus is F25, what version will be available ?
Can you make sure to update strings and make us translate the good content ?
And be available to release minor version so it gets in F25 ?

**Comment by tsmetana** [comment]
I have filed the [PR#87](https://github.com/storaged-project/storaged/pull/87l). There's the new translations together with the storaged->udisks renaming.  If nobody spots any issues with the PR I will push the updates to Zanata too. (I'm not that familiar with Zanata yet.)

As for F25: there's the 2.6.2-2 in the testing repo right now. The 2.6+ version is meant to be a drop-in udisks2 replacement and doesn't try to hide the fact it's a direct udisks2 fork. So there's been some changes (mostly "mechanical").

**Comment by Jibec** [comment]
have you push new content to Zanata ? I see last update is from 10/09/2016, is it up to date yet ?

**Comment by Jibec** [comment]
ok, when do you plan to push content in Zanata ?

**Comment by tsmetana** [comment]
HI. As soon as I get to that. There's too many things I have to handle right now, just as the other stroraged folks who review the PRs... I can merge without an ack, but prefer someone else to scan my patches.

**Comment by Jibec** [comment]
More than a month that I asked for help, this is not very encouraging regarding foreign language support... Please help.

**Comment by tsmetana** [comment]
I have merged the new translations and updated the po files. I will push the content to Zanata (need to get permissions to do that first).

**Comment by tsmetana** [comment]
Stuff pushed to Zanata. Special thanks to @phatina for granting me the permissions.

**Comment by piotrdrag** [comment]
Something might have gone wrong - all storaged translations in Zanata are empty right now.

**Comment by lonemadmax** [comment]
It seems there's been a change in document name, and no merge. I can't say anything about the actions from the owner side, but translators can merge the old strings and then work in the few new strings.

**Comment by piotrdrag** [comment]
I'd really prefer that something was done on the developers side, so the translation loss would be minimized as much as possible.

**Comment by tsmetana** [comment]
Duh... So the sources rename really didn't go well.

**Comment by tsmetana** [comment]
OK. I had to push the translations to zanata. Can't tell how much damage did I make with the file shuffling... Hopefully not much.

**Comment by piotrdrag** [comment]
Looks good on my end!

**Comment by Jibec** [comment]
Looks fine, thank you @tsmetana 

How to make our live easy:
* Push/pull content often from Zanata
* Publish regular minor version including translations (you now have 22 languages with ~80%, a good part will be 100% soon)
